
jobs:
  build:
    working_directory: ~python-ci

machine:
  python:
    version: 3.6.7

dependencies:
  override:
    - pip install -r ../requirements.txt

test:
  override:
    - nosetests ../test/test_math.py